
#define DECLARE_TERMINAL_DESIGN(__value) "\033[" #__value "m"

#define CLI_DESIGN_RESET DECLARE_TERMINAL_DESIGN(0)
#define CLI_DESIGN_BOLD DECLARE_TERMINAL_DESIGN(1)
#define CLI_DESIGN_DIM DECLARE_TERMINAL_DESIGN(2)

#define CLI_COLOR_BLACK DECLARE_TERMINAL_DESIGN(30)
#define CLI_COLOR_RED DECLARE_TERMINAL_DESIGN(31)
#define CLI_COLOR_GREEN DECLARE_TERMINAL_DESIGN(32)
#define CLI_COLOR_YELLOW DECLARE_TERMINAL_DESIGN(33)
#define CLI_COLOR_BLUE DECLARE_TERMINAL_DESIGN(34)
#define CLI_COLOR_MAGENTA DECLARE_TERMINAL_DESIGN(35)
#define CLI_COLOR_CYAN DECLARE_TERMINAL_DESIGN(36)
#define CLI_COLOR_WHITE DECLARE_TERMINAL_DESIGN(37)

#define CLI_DESIGN_BG_RED DECLARE_TERMINAL_DESIGN(41)
#define CLI_DESIGN_BG_GREEN DECLARE_TERMINAL_DESIGN(42)
#define CLI_DESIGN_BG_YELLOW DECLARE_TERMINAL_DESIGN(43)
#define CLI_DESIGN_BG_BLUE DECLARE_TERMINAL_DESIGN(44)

#define CLI_COLOR_BRIGHT_BLACK DECLARE_TERMINAL_DESIGN(90)
#define CLI_COLOR_BRIGHT_RED DECLARE_TERMINAL_DESIGN(91)
#define CLI_COLOR_BRIGHT_GREEN DECLARE_TERMINAL_DESIGN(92)
#define CLI_COLOR_BRIGHT_YELLOW DECLARE_TERMINAL_DESIGN(93)
#define CLI_COLOR_BRIGHT_BLUE DECLARE_TERMINAL_DESIGN(94)
#define CLI_COLOR_BRIGHT_MAGENTA DECLARE_TERMINAL_DESIGN(95)
#define CLI_COLOR_BRIGHT_CYAN DECLARE_TERMINAL_DESIGN(96)
#define CLI_COLOR_BRIGHT_WHITE DECLARE_TERMINAL_DESIGN(97)

#define COLOR_TEXT(__color, __text) __color __text CLI_DESIGN_RESET

#ifdef __cplusplus

namespace CliColors
{

    #define CREATE_CLI_COLOR(__name) constexpr const char*const __name = CLI_COLOR_##__name
    #define CREATE_CLI_DESIGN(__design) constexpr const char*const __design = CLI_DESIGN_##__design

    CREATE_CLI_DESIGN(RESET);
    CREATE_CLI_DESIGN(BOLD);
    CREATE_CLI_DESIGN(DIM);

    CREATE_CLI_COLOR(BLACK);
    CREATE_CLI_COLOR(RED);
    CREATE_CLI_COLOR(GREEN);
    CREATE_CLI_COLOR(YELLOW);
    CREATE_CLI_COLOR(BLUE);
    CREATE_CLI_COLOR(MAGENTA);
    CREATE_CLI_COLOR(CYAN);
    CREATE_CLI_COLOR(WHITE);

    CREATE_CLI_DESIGN(BG_RED);
    CREATE_CLI_DESIGN(BG_GREEN);
    CREATE_CLI_DESIGN(BG_YELLOW);
    CREATE_CLI_DESIGN(BG_BLUE);

    CREATE_CLI_COLOR(BRIGHT_BLACK);
    CREATE_CLI_COLOR(BRIGHT_RED);
    CREATE_CLI_COLOR(BRIGHT_GREEN);
    CREATE_CLI_COLOR(BRIGHT_YELLOW);
    CREATE_CLI_COLOR(BRIGHT_BLUE);
    CREATE_CLI_COLOR(BRIGHT_MAGENTA);
    CREATE_CLI_COLOR(BRIGHT_CYAN);
    CREATE_CLI_COLOR(BRIGHT_WHITE);
}
#endif
